CREATE TABLE IF NOT EXISTS links (
  id VARCHAR PRIMARY KEY,
  original_url VARCHAR NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stats (
  id SERIAL PRIMARY KEY,
  link_id VARCHAR NOT NULL,
  ip VARCHAR NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_link FOREIGN KEY (link_id) REFERENCES links(id) ON DELETE CASCADE
);
